In [1]:
# Consider the below code to answer further questions:

In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [3]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Solution 1-

<span style  = 'font-size:0.8em;'>
    
Yes, there is a difference in the data type of `list_` and `array_list`. `list_` is a Python list, while `array_list` is a NumPy array. we can print the data types of both variables using the `type()` function in Python. Here's the code:
</span>

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [5]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

### Solution 2-

In [6]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Printing data type of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Printing data type of each element in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [7]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# and arra_list.

### Solution 3-

<span style  = 'font-size:0.8em;'>

Yes, there will be a difference in the data type of the elements present in list_ and array_list after the change in the creation of array_list where the dtype parameter is set to int.
</span>

In [8]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Printing data type of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Printing data type of each element in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [9]:
# Consider the below code to answer further questions:

In [10]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [11]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [12]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

### Solution 4-

In [14]:
# (i) Finding the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

Shape of num_array: (2, 3)


In [15]:
# (ii) Finding the size of num_array
size = num_array.size
print("Size of num_array:", size)

Size of num_array: 6


In [16]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

### Solution 5-

In [17]:
# Creating a 3x3 matrix containing zeros
zeros_array = np.zeros((3, 3))

In [18]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

### Solution 6-

In [20]:
# Creating an identity matrix of shape (5,5)
identity_matrix = np.eye(5)

In [21]:
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])